version: '4'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
        - "5998:5432"
    volumes:
        - ./data:/var/lib/postgresql/data
